# Usar una imagen base de Java
FROM openjdk:17

# Establecer el directorio de trabajo en /app
WORKDIR /app

# Copiar el JAR de la aplicación al contenedor
COPY target/my-spring-boot-app.jar /app

# Exponer el puerto en el que se ejecuta la aplicación
EXPOSE 8080

# Comando para ejecutar la aplicación cuando se inicie el contenedor
CMD ["java", "-jar", "my-spring-boot-app.jar"]
